In [58]:
import pandas as pd
import numpy as np

df = pd.read_csv('movie_rv.csv')

In [3]:
df.isna().sum()

Unnamed: 0    0
id            0
document      5
label         0
dtype: int64

In [59]:
#na값 처리
df['document'] = df['document'].fillna(0)
df['document'] = df['document'].astype(str)

#df['document'].iloc[:10000]

In [60]:
df_docu_sp2=df['document'].iloc[:50000]

In [61]:
df_docu_sp2

0                                      아 더빙.. 진짜 짜증나네요 목소리
1                        흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나
2                                        너무재밓었다그래서보는것을추천한다
3                            교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정
4        사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...
                               ...                        
49995    "이게 소위 스페인식 Neo-realism 이란 건가? - 물론, ""아동 판타지"...
49996                                     보지마셈 저 믿으세요 보지마셈
49997                                                 최고졸작
49998                                    재밌고 좋았음 10자 쓰라고?!
49999                                 소박하지만 잔잔한 감동을 주는 영화.
Name: document, Length: 50000, dtype: object

In [62]:
df_docu_sp2.isna().sum()

0

## CountVectorize 
- bow 카운트 기반으로 (카운팅을 하여서 전처리를 진행하는 것)
- 학습하기 위해서 어떤 식으로 벡터를 만들어야 하는지 확인

In [63]:
from sklearn.feature_extraction.text import CountVectorizer

# max_featrue 빈도기반으로 우선순위로 100, 1,000개 ,10,000 개등 본인이 원하는 피처를 제한을 둘 수 있다.

In [34]:
df['document']

0                                       아 더빙.. 진짜 짜증나네요 목소리
1                         흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나
2                                         너무재밓었다그래서보는것을추천한다
3                             교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정
4         사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...
                                ...                        
149995                                                  NaN
149996                                                  NaN
149997                                                  NaN
149998                                                  NaN
149999                                                  NaN
Name: document, Length: 150000, dtype: object

In [64]:
re_cv = CountVectorizer(max_features=1000) # 1000개의 피처만 가지고 옴

In [65]:
# 리뷰 데이터를 이 안에 넣어봄, 추후 더 좋은 성능을 위해서는 전처리 작업 필수

re_dtm =re_cv.fit_transform(df_docu_sp2)

In [66]:
re_dtm

<50000x1000 sparse matrix of type '<class 'numpy.int64'>'
	with 124124 stored elements in Compressed Sparse Row format>

### 행은 15만개, 열은 1,000개 제한 (1000개의 컬럼은 카운트기반으로 가장많이 나온 것으로 선정)

- Sparse 0이 얼마나 많은지에 대한 값들도 확인할 수 있음

In [67]:
#sparse 간단한 계산 
(50000/(124124*1000)*100) #

0.040282298346814474

In [68]:
re_cv.get_feature_names_out()[:100]

array(['0점', '0점은', '10', '10자', '10점', '1점', '1점도', '2점', '3류', '3점',
       '4점', '80년대', '90년대', '9점', 'b급', 'good', 'oo', 'ooo', 'ooo기',
       'ost', 'the', 'tv', 'ㄷㄷ', 'ㅅㅂ', 'ㅇㅇ', 'ㅉㅉ', 'ㅋㅋ', 'ㅋㅋㅋ', 'ㅋㅋㅋㅋ',
       'ㅋㅋㅋㅋㅋ', 'ㅎㅎ', 'ㅎㅎㅎ', 'ㅜㅜ', 'ㅠㅠ', 'ㅠㅠㅠ', 'ㅡㅡ', '가끔', '가는', '가볍게',
       '가서', '가슴', '가슴이', '가장', '가지고', '가진', '각본', '간만에', '갈수록', '감독',
       '감독님', '감독은', '감독의', '감독이', '감동', '감동과', '감동도', '감동을', '감동이',
       '감동적이고', '감동적인', '감사합니다', '갑자기', '강추', '같네요', '같다', '같습니다', '같아서',
       '같아요', '같은', '같은데', '같음', '같이', '개봉', '개뿔', '개연성', '개인적으로', '거의',
       '건지', '걸작', '겁나', '것도', '것은', '것을', '것이', '것이다', '게다가', '결국', '결말',
       '결말도', '결말은', '결말이', '계속', '공감이', '공포', '공포영화', '과연', '괜찮은', '괜히',
       '굉장히', '구성'], dtype=object)

### okt를 이용해서 동사, 명사만 추출

In [69]:
from konlpy.tag import Okt

In [70]:
tw_tag= Okt()

In [71]:
print('전체 형태소 추출 ',tw_tag.morphs(df.document[1]))
print('명사만 추출 ',tw_tag.nouns(df.document[1]))
print('태그 같이추출 ',tw_tag.pos(df.document[1]))

전체 형태소 추출  ['흠', '...', '포스터', '보고', '초딩', '영화', '줄', '....', '오버', '연기', '조차', '가볍지', '않구나']
명사만 추출  ['흠', '포스터', '보고', '초딩', '영화', '줄', '오버', '연기']
태그 같이추출  [('흠', 'Noun'), ('...', 'Punctuation'), ('포스터', 'Noun'), ('보고', 'Noun'), ('초딩', 'Noun'), ('영화', 'Noun'), ('줄', 'Noun'), ('....', 'Punctuation'), ('오버', 'Noun'), ('연기', 'Noun'), ('조차', 'Josa'), ('가볍지', 'Adjective'), ('않구나', 'Verb')]


## 전체 데이터에 적용해야 하니깐 위에는 1개 샘플만 가지고 진행
- 함수를 하나 만들고 전체 데이터셋을 다 전처리 진행

In [72]:
def my_tokenizer(doc):
    return[
        token
        for token, pos in tw_tag.pos(doc)
        if pos in ['Noun','Verb']
    ]

print('실제 결과는', my_tokenizer(df.document[1]))

실제 결과는 ['흠', '포스터', '보고', '초딩', '영화', '줄', '오버', '연기', '않구나']


In [73]:
#사용할 토큰을 지정 가능
re_cv = CountVectorizer(max_features=1000, tokenizer = my_tokenizer )

In [75]:
re_dtm =re_cv.fit_transform(df_docu_sp2)

/opt/anaconda3/envs/bda/lib/python3.8/site-packages/sklearn/feature_extraction/text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


In [76]:
#어떤 식으로 카운팅 기반으로 되어 있는지 확인
for word, count in zip(re_cv.get_feature_names_out(), re_dtm[1].toarray()[0]):
    if count>0:
        print(word,count,end=',')

보고 1,연기 1,영화 1,줄 1,초딩 1,포스터 1,흠 1,

### 리뷰데이터를 카운팅해서 하나의 데이터프레임으로 만들고 있다.
- 50,000개의 행, 1,000개의 컬럼으로 만들었다.

## 간단하게 Cosine_Similarity 를 확인

In [85]:
from sklearn.metrics.pairwise import cosine_similarity

# 기준으로 볼 리뷰를 하나 가져옴
st = len(df_docu_sp2[0])//2

# 중심점으로부터 뒤 절반을 가지고 와서 비교할 문서를 생성
source = df_docu_sp2[0][-st:]

In [82]:
df_docu_sp2[0]

'아 더빙.. 진짜 짜증나네요 목소리'

In [84]:
st

9

In [86]:
source

'짜증나네요 목소리'

In [145]:
#코사인 유사도를 게산하기 위해 벡터로 변환
source_rv=re_cv.transform([source])

In [146]:
source_rv

<1x1000 sparse matrix of type '<class 'numpy.int64'>'
	with 1 stored elements in Compressed Sparse Row format>

In [147]:
source_rv

<1x1000 sparse matrix of type '<class 'numpy.int64'>'
	with 1 stored elements in Compressed Sparse Row format>

In [89]:
sim_res=cosine_similarity(source_rv,re_dtm)

In [90]:
sim_res

array([[0.57735027, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [93]:
sim_res[0]

array([0.57735027, 0.        , 0.        , ..., 0.        , 0.        ,
       0.        ])

In [94]:
#유사도 계산 결과가 어떤식으로 되어 있는지 역순으로 정렬
print('유사도 정렬',sorted(sim_res[0], reverse=True)[:100])

유사도 정렬 [1.0, 1.0, 0.8944271909999159, 0.8164965809277261, 0.7559289460184544, 0.7071067811865475, 0.7071067811865475, 0.7071067811865475, 0.7071067811865475, 0.7071067811865475, 0.7071067811865475, 0.7071067811865475, 0.7071067811865475, 0.7071067811865475, 0.7071067811865475, 0.7071067811865475, 0.7071067811865475, 0.7071067811865475, 0.7071067811865475, 0.6963106238227914, 0.5773502691896258, 0.5773502691896258, 0.5773502691896258, 0.5773502691896258, 0.5773502691896258, 0.5773502691896258, 0.5773502691896258, 0.5773502691896258, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.48507125007266594, 0.47140452079103173, 0.4472135954999579, 0.4472135954999579, 0.4472135954999579, 0.4472135954999579, 0.4472135954999579, 0.4472135954999579, 0.4472135954999579, 0.4082482904638631, 0.4082482904638631, 0.4082482904638631, 0.4082482904638631, 0.4082482904638631, 0.4082482904638631, 0.3779644730092272, 0.3779644730092272, 0.3779644730092272, 0.3779644730092272, 0.3779644730092

In [95]:
#리뷰가 어떤 리뷰인지 유사한 리뷰가 무엇인지 확인
print('가장 유사한 리뷰는 무엇인지?',np.argmax(sim_res[0]))

가장 유사한 리뷰는 무엇인지? 7876


In [96]:
df_docu_sp2[7876]

'김용만의 목소리가 좋았다.'

In [108]:
df_docu_sp2[33311]

'정말 내인생 최고의 영화'

In [105]:
print(sim_res[0].argsort()[3])

33311


### 카운트기반으로 하는 게 문제가 많음
- 단어가 더 많다고 해서 꼭 중요한 건 아닐 수 있다.
- 이런 의미를 좀 반영해서 전처리 하는 방법이 TF-IDF(Term Frequency - Inverse Document Frequency) 
- 단어빈도 - 역문서빈도

- 카운트 대신 단어의 빈도에 그 단어가 출연한 문서의 수를 역수를 곱하는 것
- 단어의 빈도를 그 단어가 나타난 문서의 수로 나눠 준 것
- 단어가 나타난 문서의 수가 클수록 이 값이 작아지니 단순하게 카운팅 한 것 보다는 빈도를 이용해서 계산하게 되니 더 의미있는 단어를 추출할 수 있다.

In [110]:
from sklearn.feature_extraction.text import TfidfTransformer

transformer = TfidfTransformer()
transformer

TfidfTransformer()

In [111]:
rv_tfidf =transformer.fit_transform(re_dtm)

In [112]:
rv_tfidf

<50000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 227438 stored elements in Compressed Sparse Row format>

In [123]:
re_dtm[10].toarray()[0] #맨처음 만든 re_dtm의 배열이 어떤식으로 되어있는지 확인이 가능
#카운트 기반은 대부분 0 1,2 정수

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [124]:
rv_tfidf[0].toarray()[0] # tf_idf 카운팅이 아닌 확률처럼 소수로 되어있음. (빈도기반)

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [125]:
source

'짜증나네요 목소리'

In [141]:
tf = TfidfTransformer()
rv_tfidf=tf.fit_transform(re_dtm)

In [150]:
source_idf=tf.transform(source_rv)

In [151]:
source_idf

<1x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 1 stored elements in Compressed Sparse Row format>

In [152]:
sim_res_tfidf=cosine_similarity(source_idf,rv_tfidf)

In [155]:
sim_res_tfidf[0]

array([0.67803893, 0.        , 0.        , ..., 0.        , 0.        ,
       0.        ])

In [158]:
print('가장 유사한 리뷰는 무엇인지?',np.argmax(sim_res_tfidf[0]))

가장 유사한 리뷰는 무엇인지? 7876


In [159]:
df_docu_sp2[7876]

'김용만의 목소리가 좋았다.'

### 두 가지 방법으로 문자열 데이터를 전처리하고, 벡터로 만들어서 코사인 유사도를 계산
- ml 분류, 감성분석 등을 진행하게 되면 이 부분도 결국에는 동일하게 벡터화로 만들어서 학습을 시켜야 된다.

In [160]:
df

Unnamed: 0        id   
0                0   9976970  \
1                1   3819312   
2                2  10265843   
3                3   9045019   
4                4   6483659   
...            ...       ...   
149995      149995   6222902   
149996      149996   8549745   
149997      149997   9311800   
149998      149998   2376369   
149999      149999   9619869   

                                                 document  label  
0                                     아 더빙.. 진짜 짜증나네요 목소리      0  
1                       흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1  
2                                       너무재밓었다그래서보는것을추천한다      0  
3                           교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0  
4       사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...      1  
...                                                   ...    ...  
149995                                인간이 문제지.. 소는 뭔죄인가..      0  
149996                                      평점이 너무 낮아서...      1  
149997                    이게 뭐요? 한국인은 거들먹거리고 필리핀 혼혈은 착하다?      0  
149998                        청춘 영화의 최고봉.방황과 우울했던 날들의 자화상      1  
149999                           한국 영화 최초로 수간하는 내용이 담긴 영화      0  

[150000 rows x 4 columns]